
services:
  app:
    build:
      context: ./hosting-app  # Измените контекст сборки
      dockerfile: ../dockerfiles/php/Dockerfile
    volumes:
      - ./hosting-app:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./hosting-app:/var/www
      - ./dockerfiles/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: